[24-Apr-2025 08:09:30 Europe/Berlin] Python script execution failed
[24-Apr-2025 08:13:32 Europe/Berlin] Python execution failed
[24-Apr-2025 08:14:12 Europe/Berlin] Python execution failed
[24-Apr-2025 08:18:58 Europe/Berlin] Python script execution failed
[24-Apr-2025 08:18:58 Europe/Berlin] Python script execution failed
[24-Apr-2025 08:18:59 Europe/Berlin] Python script execution failed
[24-Apr-2025 08:25:13 Europe/Berlin] Invalid response from Python: {"error": "Exception occurred: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 08:29:02 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 09:41:34 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 09:49:28 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 09:57:03 Europe/Berlin] PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 63
[24-Apr-2025 09:57:03 Europe/Berlin] Invalid response from Python: 
[24-Apr-2025 09:57:17 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:06:09 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:11:30 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:13:45 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:14:58 Europe/Berlin] Invalid response from Python: {"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:25:49 Europe/Berlin] Invalid response from Python: Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:30:38 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:30:38 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:31:45 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
{"error": "Exception: could not convert string to float: 'Normal'"}

[24-Apr-2025 10:31:45 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
{"error": "Exception: could not convert string to float: 'Normal'"}

[24-Apr-2025 10:32:07 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:32:07 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:34:33 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
{"error": "Invalid number of arguments"}

[24-Apr-2025 10:34:33 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
{"error": "Invalid number of arguments"}

[24-Apr-2025 10:37:23 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:37:23 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:42:21 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:42:21 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:42:22 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:42:22 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:43:15 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:43:15 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:44:01 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:44:01 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:44:44 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:44:44 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:45:10 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:45:10 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:45:32 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:45:32 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:00 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:00 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:45 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:45 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:51 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:46:51 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:47:19 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:47:19 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:47:29 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:47:29 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:49:39 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:49:39 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:50:33 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:50:33 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:51:02 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:51:02 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:53:25 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[24-Apr-2025 10:53:25 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[26-Apr-2025 18:00:24 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[26-Apr-2025 18:00:24 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[26-Apr-2025 18:00:25 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[26-Apr-2025 18:00:25 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:11:18 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:11:18 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:24:15 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:24:15 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:51:59 Europe/Berlin] Python script output: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 09:51:59 Europe/Berlin] Invalid response from Python: Model path: C:\xampp\htdocs\pdd\heart_svm_13.pkl
Loading model...
Model loaded successfully.
Processing input arguments...
Making prediction...
{"error": "Exception: 'SVC' object has no attribute '_probA'"}

[27-Apr-2025 14:39:34 Europe/Berlin] Python script execution failed: 
[27-Apr-2025 17:30:16 Europe/Berlin] Python script execution failed: 
[27-Apr-2025 17:38:10 Europe/Berlin] Python script execution failed: 
[27-Apr-2025 17:52:38 Europe/Berlin] Python script execution failed: 
[27-Apr-2025 18:00:43 Europe/Berlin] Python script execution failed: 
[27-Apr-2025 18:03:19 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:09:16 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:11:35 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:32:42 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:38:38 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:42:07 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:58
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(58): mysqli_stmt->bind_param('iiiiiiiiddddid', 1, 39, 4, 0, 0, 0, 0, 0, 0, 195.0, 106.0, 70.0, 26.97, 80, 77.0)
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 58
[27-Apr-2025 18:43:11 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:58
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(58): mysqli_stmt->bind_param('iiiiiiiiddddid', 1, 30, 4, 0, 0, 0, 0, 0, 0, 100.0, 20.0, 20.0, 26.97, 120, 100.0)
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 58
[27-Apr-2025 18:47:11 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 18:59:45 Europe/Berlin] Python output: The system cannot find the path specified.

[27-Apr-2025 19:40:54 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:58
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(58): mysqli_stmt->bind_param('iiiiiiiiddddid', 1, 20, 3, 0, 0, 0, 0, 0, 0, 150.0, 100.0, 20.0, 26.7, 120, 100.0)
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 58
[27-Apr-2025 19:54:20 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:58
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(58): mysqli_stmt->bind_param('iiiiiiiiddddid', 1, 20, 3, 0, 0, 0, 0, 0, 0, 150.0, 100.0, 20.0, 26.7, 120, 100.0)
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 58
[28-Apr-2025 07:09:42 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:61
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(61): mysqli_stmt->bind_param('iiiiiiiiiiiddi', '1', '20', '2', '0', '0', '0', '1', '0', '0', '120', '100', '160', '26.7', '120', '100')
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 61
[28-Apr-2025 07:10:29 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:61
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(61): mysqli_stmt->bind_param('iiiiiiiiiiiddi', '1', '20', '3', '0', '0', '0', '0', '0', '0', '120', '100', '120', '80', '120', '100')
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 61
[28-Apr-2025 07:13:19 Europe/Berlin] Missing field: weight
[28-Apr-2025 07:13:36 Europe/Berlin] Missing field: weight
[28-Apr-2025 07:16:57 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in C:\xampp\htdocs\pdd\Frontend\fill_detail.php:69
Stack trace:
#0 C:\xampp\htdocs\pdd\Frontend\fill_detail.php(69): mysqli_stmt->bind_param('iisssiiisiiiii', '1', '20', '1', '0', '0', '0', '0', '0', '0', '120', '100', '120', '80', '120', '100')
#1 {main}
  thrown in C:\xampp\htdocs\pdd\Frontend\fill_detail.php on line 69
